In [1]:
import numpy as np

In [2]:
a=np.array([[10,20,30],[50,70,60],[1,2,3]])

In [3]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [4]:
np.amin(a)

1

In [5]:
np.amax(a)

70

In [7]:
np.amin(a,axis=0) #Column-Wise

array([1, 2, 3])

In [8]:
np.amin(a,axis=1) #Row-wise

array([10, 50,  1])

In [9]:
np.amax(a,axis=0) #Column-Wise

array([50, 70, 60])

In [10]:
np.amax(a,axis=1) #Row-Wise

array([30, 70,  3])

In [12]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [11]:
np.average(a)

27.333333333333332

In [13]:
w=[1,2,3]

In [16]:
np.average(a,weights=w,axis=0) #(10*1+20*50+3*1)/(1+2+3)

array([18.83333333, 27.66666667, 26.5       ])

In [17]:
np.average(a,weights=w,axis=1)

array([23.33333333, 61.66666667,  2.33333333])

In [18]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [19]:
np.mean(a)

27.333333333333332

In [20]:
np.mean(a,axis=0) #(10+50+1)/3

array([20.33333333, 30.66666667, 31.        ])

In [21]:
np.mean(a,axis=1)

array([20., 60.,  2.])

In [22]:
np.median(a) #middle element after sorting in ascending order

20.0

In [23]:
np.median(a,axis=0)

array([10., 20., 30.])

In [24]:
np.median(a,axis=1)

array([20., 60.,  2.])

In [25]:
np.var(a)

632.2222222222223

In [26]:
np.std(a)

25.144029554194816